version: '3'
services:
  web:
    image: nginx:1.13.5-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html

  app:
    image: php:7.1.9-fpm-alpine
